### ISSUE TITLE
Error [TypeError]: Cannot read property 'Key' of undefined

### ISSUE THREAD

**Issue by PoornaYaganti** [shallwefootball/upload-s3-action#44]
Getting the following error when I try to upload GitHub artifacts to S3.

B```
adRequest: null
/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.3/dist/index.js:6786
            throw err;
            ^

Error [TypeError]: Cannot read property 'Key' of undefined
    at ManagedUpload.callback (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.3/dist/index.js:2459:36)
    at Response.finishSinglePart (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.3/dist/index.js:20929:[28](https://github.com/ZscalerCWP/cwp-qaautomation-robotframework/actions/runs/3106021913/jobs/5032368042#step:8:29))
    at Request.<anonymous> (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.3/dist/index.js:7124:18)
    at Request.callListeners (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.3/dist/index.js:11458:20)
    at Request.emit (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.3/dist/index.js:114[30](https://github.com/ZscalerCWP/cwp-qaautomation-robotframework/actions/runs/3106021913/jobs/5032368042#step:8:31):10)
    at Request.emit (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.3/dist/index.js:7443:14)
    at Request.transition (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.3/dist/index.js:6777:10)
    at AcceptorStateMachine.runTo (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.3/dist/index.js:14564:12)
    at /home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.3/dist/index.js:14576:10
    at Request.<anonymous> (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.1.3/dist/index.js:6793:9) {
  code: 'TypeError',
  time: 2022-09-22T13:53:20.7[31](https://github.com/ZscalerCWP/cwp-qaautomation-robotframework/actions/runs/3106021913/jobs/5032368042#step:8:32)Z
}
```

**Comment by nabeelio** [comment]
Same here. 

```
Error: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:6786
            throw err;
            ^

Error [TypeError]: Cannot read property 'Key' of undefined
    at ManagedUpload.callback (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:2459:36)
    at Response.finishSinglePart (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:20929:28)
    at Request.<anonymous> (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:7124:18)
    at Request.callListeners (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:11458:20)
    at Request.emit (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:11430:10)
    at Request.emit (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:7443:14)
    at Request.transition (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:6777:10)
    at AcceptorStateMachine.runTo (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:14564:12)
    at /home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:14576:10
    at Request.<anonymous> (/home/runner/work/_actions/shallwefootball/s3-upload-action/master/dist/index.js:6793:9) {
  code: 'TypeError',
  time: 2022-10-10T19:41:09.934Z
}
```

**Comment by schenniappan-symplr** [comment]
I am also facing the same issue. what is the solution.

**Comment by StephanMertel** [comment]
This doesn't seem to be maintained  anymore... I ended up using https://github.com/aws-actions/configure-aws-credentials

**Comment by nabeelio** [comment]
> This doesn't seem to be maintained  anymore... I ended up using https://github.com/aws-actions/configure-aws-credentials

Same, ended up being much easier

**Comment by srijeyanthan-cerexio** [comment]
Same, we need the region passed to configuration, but not supported by this library so far, end-up using confgure-aws-credentials, much easier.
