### ISSUE TITLE
A problem with parameters

### ISSUE THREAD

**Issue by ssichynskyi** [shallwefootball/upload-s3-action#5]
in docu there are 2 parameters for the same purposes:
aws_secret_access-key
and
aws_secret_access_key
(underscore vs dash)

1. if "aws_secret_access-key" first one is used, then action fails with this log:
>>
/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:9494
        throw new Error(`Input required and not supplied: ${name}`);
        ^

Error: Input required and not supplied: aws_secret_access_key
    at Object.getInput (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:9494:15)
    at Object.104 (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:2408:32)
    at __webpack_require__ (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:22:30)
    at startup (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:37:19)
    at /home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:41:18
    at Object.<anonymous> (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:44:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)

2.  if "aws_secret_access_key" first one is used, then action fails with this log:
/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:8307
            throw err;
            ^

Error [TypeError]: (s || "").replace is not a function
    at escapeData (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:8121:10)
    at Command.toString (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:8115:35)
    at issueCommand (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:8078:30)
    at Object.issue (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:8082:5)
    at Object.error (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:9545:15)
    at ManagedUpload.callback (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:2430:21)
    at ManagedUpload.cleanup (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:20775:10)
    at Request.<anonymous> (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:20654:16)
    at Request.callListeners (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:12939:20)
    at Request.emit (/home/runner/work/_actions/shallwefootball/upload-s3-action/v1.0.0/dist/index.js:12911:10) {
  message: '(s || "").replace is not a function',
  code: 'TypeError',
  time: 2020-05-30T16:18:47.741Z
}

IN ANY CASE, ACTION DOES NOT WORK (at least for me)

**Comment by shallwefootball** [comment]
yap fix this. #4

**Comment by phuongTP1998** [comment]
Still met this kind of error even though changed to v1.0.1
![Screen Shot 2021-05-24 at 09 40 11](https://user-images.githubusercontent.com/27052181/119289042-0ae5e980-bc74-11eb-997a-35a93ca049fb.png)
